/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef UINT128_TRAITS_SPECIALIZATIONS_HPP
#define UINT128_TRAITS_SPECIALIZATIONS_HPP

/**
 * @file uint128_traits_specializations.hpp
 * @brief Forward declarations for nstd::uint128_t type traits specializations
 *
 * ⚠️ CRITICAL: This header MUST be included BEFORE <type_traits> is included
 * for the first time. Otherwise, the specializations will not be recognized.
 *
 * This header only contains forward declarations and specializations for
 * std::type_traits. It does NOT include nstd::uint128_t.hpp to avoid circular
 * dependencies and ensure traits are available when type_traits is first included.
 */

// Forward declare nstd::uint128_t (do NOT include uint128_t.hpp here!)
namespace nstd
{
class uint128_t;
class int128_t;
} // namespace nstd

// Detectar si las especializaciones de traits están disponibles
// NO están disponibles en:
// - libc++ (Clang con libc++)
// - MSVC STL (Microsoft Visual C++)
// - Intel ICX en Windows (usa MSVC STL que no permite especializaciones)
#if defined(_LIBCPP_VERSION)
#define UINT128_USING_LIBCPP 1
#elif defined(_MSC_VER) && !defined(__INTEL_LLVM_COMPILER)
#define UINT128_USING_LIBCPP 1 // MSVC STL también bloquea especializaciones
#elif defined(__INTEL_LLVM_COMPILER) && defined(_MSC_VER)
#define UINT128_USING_LIBCPP 1
#else
#define UINT128_USING_LIBCPP 0
#endif

// ⚠️ IMPORTANT: Include type_traits HERE, before the specializations
#include <type_traits>

namespace std
{

// ===============================================================================
// TYPE TRAITS FUNDAMENTALES PARA nstd::uint128_t
// ===============================================================================

#if !UINT128_USING_LIBCPP

template <> struct is_integral<nstd::uint128_t> : true_type {
};
template <> struct is_arithmetic<nstd::uint128_t> : true_type {
};
template <> struct is_unsigned<nstd::uint128_t> : true_type {
};
template <> struct is_signed<nstd::uint128_t> : false_type {
};
template <> struct is_trivially_copyable<nstd::uint128_t> : true_type {
};
template <> struct is_trivially_constructible<nstd::uint128_t> : true_type {
};
template <> struct is_trivially_default_constructible<nstd::uint128_t> : true_type {
};
template <> struct is_trivially_copy_constructible<nstd::uint128_t> : true_type {
};
template <> struct is_trivially_move_constructible<nstd::uint128_t> : true_type {
};
template <> struct is_trivially_assignable<nstd::uint128_t, nstd::uint128_t> : true_type {
};
template <> struct is_trivially_copy_assignable<nstd::uint128_t> : true_type {
};
template <> struct is_trivially_move_assignable<nstd::uint128_t> : true_type {
};
template <> struct is_trivially_destructible<nstd::uint128_t> : true_type {
};
template <> struct is_standard_layout<nstd::uint128_t> : true_type {
};

#endif // !UINT128_USING_LIBCPP

// ===============================================================================
// TYPE TRAITS FUNDAMENTALES PARA nstd::int128_t
// ===============================================================================

#if !UINT128_USING_LIBCPP

template <> struct is_integral<nstd::int128_t> : true_type {
};
template <> struct is_arithmetic<nstd::int128_t> : true_type {
};
template <> struct is_unsigned<nstd::int128_t> : false_type {
};
template <> struct is_signed<nstd::int128_t> : true_type {
};
template <> struct is_trivially_copyable<nstd::int128_t> : true_type {
};
template <> struct is_trivially_constructible<nstd::int128_t> : true_type {
};
template <> struct is_trivially_default_constructible<nstd::int128_t> : true_type {
};
template <> struct is_trivially_copy_constructible<nstd::int128_t> : true_type {
};
template <> struct is_trivially_move_constructible<nstd::int128_t> : true_type {
};
template <> struct is_trivially_assignable<nstd::int128_t, nstd::int128_t> : true_type {
};
template <> struct is_trivially_copy_assignable<nstd::int128_t> : true_type {
};
template <> struct is_trivially_move_assignable<nstd::int128_t> : true_type {
};
template <> struct is_trivially_destructible<nstd::int128_t> : true_type {
};
template <> struct is_standard_layout<nstd::int128_t> : true_type {
};

// ===============================================================================
// CONVERSIONES SIGNED/UNSIGNED
// ===============================================================================

/**
 * @brief Especialización de std::make_signed para nstd::uint128_t
 *
 * Convierte nstd::uint128_t a su equivalente con signo (nstd::int128_t)
 */
template <> struct make_signed<nstd::uint128_t> {
    using type = nstd::int128_t;
};

// NOTA: make_unsigned<nstd::int128_t> está definido en int128_traits.hpp

#endif // !UINT128_USING_LIBCPP

} // namespace std
#endif // UINT128_TRAITS_SPECIALIZATIONS_HPP
