/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef UINT128_RANGES_HPP
#define UINT128_RANGES_HPP

#include "uint128_t.hpp"
#include <array>
#include <numeric>
#include <vector>

/**
 * @brief Funciones de rango optimizadas para uint128_t
 *
 * Este archivo proporciona implementaciones especializadas y optimizadas
 * de funciones de rango estándar para trabajar con uint128_t.
 */

namespace uint128_ranges
{

using uint128_t = nstd::uint128_t;
using int128_t = nstd::int128_t;

/**
 * @brief Llena un rango con valores secuenciales incrementales
 * Equivalente a std::iota pero optimizado para uint128_t
 */
template <class ForwardIt> void iota(ForwardIt first, ForwardIt last, uint128_t value)
{
    while (first != last) {
        *first++ = value;
        ++value;
    }
}

/**
 * @brief Acumula valores en un rango
 * Equivalente a std::accumulate optimizado para uint128_t
 */
template <class InputIt> uint128_t accumulate(InputIt first, InputIt last, uint128_t init)
{
    while (first != last) {
        init = init + *first;
        ++first;
    }
    return init;
}

/**
 * @brief Acumula valores con operación personalizada
 */
template <class InputIt, class BinaryOperation>
uint128_t accumulate(InputIt first, InputIt last, uint128_t init, BinaryOperation op)
{
    while (first != last) {
        init = op(init, *first);
        ++first;
    }
    return init;
}

/**
 * @brief Calcula el producto interno de dos rangos
 */
template <class InputIt1, class InputIt2>
uint128_t inner_product(InputIt1 first1, InputIt1 last1, InputIt2 first2, uint128_t init)
{
    while (first1 != last1) {
        init = init + (*first1) * (*first2);
        ++first1;
        ++first2;
    }
    return init;
}

/**
 * @brief Calcula las sumas parciales de un rango
 */
template <class InputIt, class OutputIt>
OutputIt partial_sum(InputIt first, InputIt last, OutputIt d_first)
{
    if (first == last)
        return d_first;

    uint128_t sum = *first;
    *d_first = sum;

    while (++first != last) {
        sum = sum + *first;
        *++d_first = sum;
    }
    return ++d_first;
}

/**
 * @brief Calcula las diferencias adyacentes de un rango
 */
template <class InputIt, class OutputIt>
OutputIt adjacent_difference(InputIt first, InputIt last, OutputIt d_first)
{
    if (first == last)
        return d_first;

    uint128_t acc = *first;
    *d_first = acc;

    while (++first != last) {
        uint128_t val = *first;
        *++d_first = val - acc;
        acc = val;
    }
    return ++d_first;
}

} // namespace uint128_ranges

// ===============================================================================
// FUNCIONES DE CONVENIENCIA EN EL NAMESPACE STD
// ===============================================================================

namespace nstd
{

/**
 * @brief Función de conveniencia para std::iota con uint128_t
 * Permite usar directamente std::iota con contenedores de uint128_t
 */
inline void iota(std::vector<uint128_t>::iterator first, std::vector<uint128_t>::iterator last,
                 uint128_t value)
{
    uint128_ranges::iota(first, last, value);
}

/**
 * @brief Función de conveniencia para arrays
 */
template <size_t N>
inline void iota(typename std::array<uint128_t, N>::iterator first,
                 typename std::array<uint128_t, N>::iterator last, uint128_t value)
{
    uint128_ranges::iota(first, last, value);
}

/**
 * @brief Función de conveniencia para std::accumulate con uint128_t
 */
inline uint128_t accumulate(std::vector<uint128_t>::iterator first,
                            std::vector<uint128_t>::iterator last, uint128_t init)
{
    return uint128_ranges::accumulate(first, last, init);
}

} // namespace nstd
#endif // UINT128_RANGES_HPP