/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef UINT128_RANGES_HPP
#define UINT128_RANGES_HPP

#include "uint128_t.hpp"
#include <numeric>

/**
 * @brief Especializaciones de funciones de rango de std para uint128_t
 *
 * Este archivo proporciona especializaciones de las funciones de rango
 * estándar (std::iota, std::accumulate, etc.) para trabajar con uint128_t.
 */

namespace std
{

/**
 * @brief Especialización de std::iota para uint128_t
 * Llena un rango con valores secuenciales incrementales
 */
template <class ForwardIt> void iota(ForwardIt first, ForwardIt last, uint128_t value)
{
    while (first != last) {
        *first++ = value;
        ++value;
    }
}

/**
 * @brief Especialización de std::accumulate para uint128_t
 */
template <class InputIt> uint128_t accumulate(InputIt first, InputIt last, uint128_t init)
{
    while (first != last) {
        init = init + *first;
        ++first;
    }
    return init;
}

/**
 * @brief Especialización de std::accumulate con operación personalizada
 */
template <class InputIt, class BinaryOperation>
uint128_t accumulate(InputIt first, InputIt last, uint128_t init, BinaryOperation op)
{
    while (first != last) {
        init = op(init, *first);
        ++first;
    }
    return init;
}

/**
 * @brief Especialización de std::inner_product para uint128_t
 */
template <class InputIt1, class InputIt2>
uint128_t inner_product(InputIt1 first1, InputIt1 last1, InputIt2 first2, uint128_t init)
{
    while (first1 != last1) {
        init = init + (*first1) * (*first2);
        ++first1;
        ++first2;
    }
    return init;
}

// NOTA: Las funciones std::partial_sum, std::adjacent_difference, etc.
// ya funcionan correctamente con uint128_t sin necesidad de especializaciones
// adicionales, ya que son templates genéricos que solo requieren operadores
// básicos (+, -, etc.) que uint128_t ya proporciona.
//
// Solo especializamos iota() y accumulate() porque toman valores por copia
// y podemos optimizar pasándolos directamente como uint128_t.

} // namespace std

#endif // UINT128_RANGES_HPP