/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef UINT128_TRAITS_HPP
#define UINT128_TRAITS_HPP

// ⚠️ IMPORTANT: Trait specializations are defined in uint128_traits_specializations.hpp
// That header MUST be included before uint128_t.hpp to ensure traits are available
// when <type_traits> is first included.
#include "uint128_traits_specializations.hpp"

#include "uint128_t.hpp"
#include <functional>
#include <type_traits>

namespace std
{

// ===============================================================================
// TYPE TRAITS FUNDAMENTALES
// ===============================================================================
// NOTE: The fundamental trait specializations (is_integral, is_arithmetic, etc.)
// are now defined in uint128_traits_specializations.hpp
// This header contains additional specializations that don't require forward declaration.

#if !UINT128_USING_LIBCPP

/**
 * @brief nstd::uint128_t es un tipo trivial
 *
 * Combina todas las propiedades triviales: constructible, copiable,
 * asignable y destructible trivialmente.
 */
template <> struct is_trivial<nstd::uint128_t> : false_type {
};

/**
 * @brief nstd::uint128_t es un tipo POD (Plain Old Data)
 *
 * Combina ser trivial y tener layout estándar.
 */
template <> struct is_pod<nstd::uint128_t> : true_type {
};

#endif // !UINT128_USING_LIBCPP

// ===============================================================================
// TRANSFORMACIÓN DE TIPOS
// ===============================================================================

#if !UINT128_USING_LIBCPP

/**
 * @brief Especialización para make_unsigned
 *
 * Para uint128_t, make_unsigned devuelve el mismo tipo ya que
 * uint128_t ya es sin signo.
 */
template <> struct make_unsigned<nstd::uint128_t> {
    using type = nstd::uint128_t;
};

/**
 * @brief Especialización para make_signed
 *
 * NOTA: Esta especialización está definida en uint128_traits_specializations.hpp
 * que se incluye desde uint128_t.hpp. No la definimos aquí para evitar conflictos.
 */

#endif // !UINT128_USING_LIBCPP

// ===============================================================================
// TIPOS COMUNES (COMMON TYPES)
// ===============================================================================

/**
 * @brief Especializaciones para common_type con tipos integrales estándar
 *
 * Estas especializaciones permiten que uint128_t se use correctamente
 * en templates que dependen de std::common_type.
 */

template <> struct common_type<nstd::uint128_t, uint64_t> {
    using type = nstd::uint128_t;
};

template <> struct common_type<uint64_t, nstd::uint128_t> {
    using type = nstd::uint128_t;
};

template <> struct common_type<nstd::uint128_t, uint32_t> {
    using type = nstd::uint128_t;
};

template <> struct common_type<uint32_t, nstd::uint128_t> {
    using type = nstd::uint128_t;
};

template <> struct common_type<nstd::uint128_t, uint16_t> {
    using type = nstd::uint128_t;
};

template <> struct common_type<uint16_t, nstd::uint128_t> {
    using type = nstd::uint128_t;
};

template <> struct common_type<nstd::uint128_t, uint8_t> {
    using type = nstd::uint128_t;
};

template <> struct common_type<uint8_t, nstd::uint128_t> {
    using type = nstd::uint128_t;
};

template <> struct common_type<nstd::uint128_t, int> {
    using type = nstd::uint128_t;
};

template <> struct common_type<int, nstd::uint128_t> {
    using type = nstd::uint128_t;
};

template <> struct common_type<nstd::uint128_t, long> {
    using type = nstd::uint128_t;
};

template <> struct common_type<long, nstd::uint128_t> {
    using type = nstd::uint128_t;
};

template <> struct common_type<nstd::uint128_t, nstd::uint128_t> {
    using type = nstd::uint128_t;
};

// NOTA: Las especializaciones common_type entre uint128_t e int128_t
// están definidas en int128_traits.hpp para evitar problemas de orden de inclusión

// ===============================================================================
// SOPORTE PARA HASH
// ===============================================================================

/**
 * @brief Especialización de std::hash para uint128_t
 *
 * Proporciona una función hash que combina los valores high y low
 * del uint128_t para su uso en containers no ordenados como
 * std::unordered_set y std::unordered_map.
 */
template <> struct hash<nstd::uint128_t> {
    /**
     * @brief Calcula el valor hash de un uint128_t
     * @param value Valor a hashear
     * @return Valor hash resultante
     *
     * La implementación combina los hashes de las partes high y low
     * usando XOR y desplazamiento para reducir colisiones.
     */
    size_t operator()(const nstd::uint128_t& value) const noexcept
    {
        hash<uint64_t> hasher;
        return hasher(value.high()) ^ (hasher(value.low()) << 1);
    }
};

} // namespace std
#endif // UINT128_TRAITS_HPP