/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef INT128_BASE_SAFE_HPP
#define INT128_BASE_SAFE_HPP

/**
 * @file int128_base_safe.hpp
 * @brief Operaciones seguras con deteccion de overflow/underflow para int128_base_t<S>
 * @details Proporciona funciones de aritmética segura (add, sub, mul, div, mod)
 * con detección de overflow/underflow para los tipos unificados int128_base_t<S>.
 * @author Julián Calderón Almendros <julian.calderon@example.com>
 * @version 1.0.0
 * @date 2026-01-10
 * @copyright Boost Software License 1.0
 */

#define INT128_BASE_SAFE_AVAILABLE 1

#include "int128_base_concepts.hpp"
#include "int128_base_tt.hpp"
#include <cmath>
#include <concepts>
#include <limits>
#include <optional>
#include <stdexcept>
#include <type_traits>

namespace nstd
{

namespace int128_safe
{

// =============================================================================
// Result types
// =============================================================================

enum class conversion_result { success, overflow, underflow, invalid_input };

template <typename T> struct safe_result {
    const T value;
    const conversion_result status;

    constexpr bool is_valid() const noexcept
    {
        return status == conversion_result::success;
    }
    constexpr explicit operator bool() const noexcept
    {
        return is_valid();
    }
    constexpr T value_or(const T& default_value) const noexcept
    {
        return is_valid() ? value : default_value;
    }
};

// =============================================================================
// Safe conversions FROM int128_base_t<S> to other types
// =============================================================================

template <signedness S, typename T>
    requires std::integral<T>
constexpr safe_result<T> safe_cast(const int128_base_t<S>& value) noexcept
{

    if constexpr (S == signedness::unsigned_type) {
        if constexpr (std::is_signed_v<T>) {
            constexpr auto max_val = static_cast<uint64_t>(std::numeric_limits<T>::max());
            if (value.high() > 0 || value.low() > max_val) {
                return {T(0), conversion_result::overflow};
            }
            return {static_cast<T>(value.low()), conversion_result::success};
        } else {
            if constexpr (sizeof(T) >= 8) {
                if (value.high() > 0) {
                    return {T(0), conversion_result::overflow};
                }
                return {static_cast<T>(value.low()), conversion_result::success};
            } else {
                constexpr auto max_val = static_cast<uint64_t>(std::numeric_limits<T>::max());
                if (value.high() > 0 || value.low() > max_val) {
                    return {T(0), conversion_result::overflow};
                }
                return {static_cast<T>(value.low()), conversion_result::success};
            }
        }
    } else {
        const bool is_negative = value.is_negative();
        const auto abs_value = value.abs();

        if constexpr (std::is_signed_v<T>) {
            constexpr auto min_val = static_cast<int64_t>(std::numeric_limits<T>::min());
            constexpr auto max_val = static_cast<int64_t>(std::numeric_limits<T>::max());

            if (abs_value.high() > 0) {
                return {T(0),
                        is_negative ? conversion_result::underflow : conversion_result::overflow};
            }

            const int64_t int64_val = is_negative ? -static_cast<int64_t>(abs_value.low())
                                                  : static_cast<int64_t>(abs_value.low());

            if (int64_val < min_val)
                return {T(0), conversion_result::underflow};
            if (int64_val > max_val)
                return {T(0), conversion_result::overflow};

            return {static_cast<T>(int64_val), conversion_result::success};
        } else {
            if (is_negative)
                return {T(0), conversion_result::underflow};

            if constexpr (sizeof(T) >= 8) {
                if (abs_value.high() > 0)
                    return {T(0), conversion_result::overflow};
                return {static_cast<T>(abs_value.low()), conversion_result::success};
            } else {
                constexpr auto max_val = static_cast<uint64_t>(std::numeric_limits<T>::max());
                if (abs_value.high() > 0 || abs_value.low() > max_val) {
                    return {T(0), conversion_result::overflow};
                }
                return {static_cast<T>(abs_value.low()), conversion_result::success};
            }
        }
    }
}

template <signedness S, typename T>
    requires std::floating_point<T>
constexpr safe_result<T> safe_cast_float(const int128_base_t<S>& value) noexcept
{

    T result;
    if constexpr (S == signedness::unsigned_type) {
        result = static_cast<T>(value.high()) * static_cast<T>(18446744073709551616.0) +
                 static_cast<T>(value.low());
    } else {
        const bool is_negative = value.is_negative();
        const auto abs_value = value.abs();
        result = static_cast<T>(abs_value.high()) * static_cast<T>(18446744073709551616.0) +
                 static_cast<T>(abs_value.low());
        if (is_negative)
            result = -result;
    }

    if (!std::isfinite(result))
        return {T(0), conversion_result::overflow};
    return {result, conversion_result::success};
}

template <signedness S, typename T> constexpr T checked_cast(const int128_base_t<S>& value)
{
    if constexpr (std::is_floating_point_v<T>) {
        const auto result = safe_cast_float<S, T>(value);
        if (!result.is_valid()) {
            throw std::overflow_error("int128 value too large for target floating point type");
        }
        return result.value;
    } else {
        const auto result = safe_cast<S, T>(value);
        if (result.status == conversion_result::overflow) {
            throw std::overflow_error("int128 value too large for target type");
        } else if (result.status == conversion_result::underflow) {
            throw std::underflow_error("int128 value too small for target type");
        }
        return result.value;
    }
}

template <signedness S, typename T>
constexpr std::optional<T> try_cast(const int128_base_t<S>& value) noexcept
{
    if constexpr (std::is_floating_point_v<T>) {
        const auto result = safe_cast_float<S, T>(value);
        return result.is_valid() ? std::make_optional(result.value) : std::nullopt;
    } else {
        const auto result = safe_cast<S, T>(value);
        return result.is_valid() ? std::make_optional(result.value) : std::nullopt;
    }
}

// =============================================================================
// Safe arithmetic operations
// =============================================================================

template <signedness S>
constexpr safe_result<int128_base_t<S>> safe_add(const int128_base_t<S>& a,
                                                 const int128_base_t<S>& b) noexcept
{
    const int128_base_t<S> result = a + b;

    if constexpr (S == signedness::unsigned_type) {
        // Overflow si result < a (wrap-around)
        if (result < a) {
            return {int128_base_t<S>(0), conversion_result::overflow};
        }
    } else {
        const bool a_neg = a.is_negative();
        const bool b_neg = b.is_negative();
        const bool r_neg = result.is_negative();

        // Positivo + Positivo = Negativo -> Overflow
        if (!a_neg && !b_neg && r_neg) {
            return {int128_base_t<S>(0), conversion_result::overflow};
        }
        // Negativo + Negativo = Positivo -> Underflow
        if (a_neg && b_neg && !r_neg) {
            return {int128_base_t<S>(0), conversion_result::underflow};
        }
    }

    return {result, conversion_result::success};
}

template <signedness S>
constexpr safe_result<int128_base_t<S>> safe_sub(const int128_base_t<S>& a,
                                                 const int128_base_t<S>& b) noexcept
{
    if constexpr (S == signedness::unsigned_type) {
        if (a < b) {
            return {int128_base_t<S>(0), conversion_result::underflow};
        }
        return {a - b, conversion_result::success};
    } else {
        const int128_base_t<S> result = a - b;
        const bool a_neg = a.is_negative();
        const bool b_neg = b.is_negative();
        const bool r_neg = result.is_negative();

        // Positivo - Negativo = Negativo -> Overflow
        if (!a_neg && b_neg && r_neg) {
            return {int128_base_t<S>(0), conversion_result::overflow};
        }
        // Negativo - Positivo = Positivo -> Underflow
        if (a_neg && !b_neg && !r_neg) {
            return {int128_base_t<S>(0), conversion_result::underflow};
        }

        return {result, conversion_result::success};
    }
}

template <signedness S>
constexpr safe_result<int128_base_t<S>> safe_mul(const int128_base_t<S>& a,
                                                 const int128_base_t<S>& b) noexcept
{
    if (a == int128_base_t<S>(0) || b == int128_base_t<S>(0)) {
        return {int128_base_t<S>(0), conversion_result::success};
    }

    if constexpr (S == signedness::unsigned_type) {
        if (a.high() != 0 && b.high() != 0) {
            return {int128_base_t<S>(0), conversion_result::overflow};
        }

        const int128_base_t<S> result = a * b;
        if (result / a != b) {
            return {int128_base_t<S>(0), conversion_result::overflow};
        }
        return {result, conversion_result::success};
    } else {
        // Trabajar con valores absolutos para verificacion de overflow
        const bool a_neg = a.is_negative();
        const bool b_neg = b.is_negative();
        const bool result_neg = (a_neg != b_neg);

        // Obtener valores absolutos como uint128_t
        const auto abs_a_temp = a.abs();
        const auto abs_b_temp = b.abs();
        const uint128_t abs_a(abs_a_temp.high(), abs_a_temp.low());
        const uint128_t abs_b(abs_b_temp.high(), abs_b_temp.low());

        if (abs_a.high() != 0 && abs_b.high() != 0) {
            return {int128_base_t<S>(0),
                    result_neg ? conversion_result::underflow : conversion_result::overflow};
        }

        const uint128_t abs_result = abs_a * abs_b;
        if (abs_result / abs_a != abs_b) {
            return {int128_base_t<S>(0),
                    result_neg ? conversion_result::underflow : conversion_result::overflow};
        }

        // Verificar que cabe en int128_t
        constexpr uint64_t max_high_positive = 0x7FFFFFFFFFFFFFFFULL;
        if (!result_neg && abs_result.high() > max_high_positive) {
            return {int128_base_t<S>(0), conversion_result::overflow};
        }
        if (result_neg && abs_result.high() > max_high_positive + 1) {
            return {int128_base_t<S>(0), conversion_result::underflow};
        }

        int128_base_t<S> result(abs_result.high(), abs_result.low());
        if (result_neg)
            result = -result;

        return {result, conversion_result::success};
    }
}

template <signedness S>
constexpr safe_result<int128_base_t<S>> safe_div(const int128_base_t<S>& a,
                                                 const int128_base_t<S>& b) noexcept
{
    if (b == int128_base_t<S>(0)) {
        return {int128_base_t<S>(0), conversion_result::invalid_input};
    }

    if constexpr (S == signedness::signed_type) {
        if (a == std::numeric_limits<int128_t>::min() && b == int128_base_t<S>(-1)) {
            return {int128_base_t<S>(0), conversion_result::overflow};
        }
    }

    return {a / b, conversion_result::success};
}

template <signedness S>
constexpr safe_result<int128_base_t<S>> safe_mod(const int128_base_t<S>& a,
                                                 const int128_base_t<S>& b) noexcept
{
    if (b == int128_base_t<S>(0)) {
        return {int128_base_t<S>(0), conversion_result::invalid_input};
    }

    if constexpr (S == signedness::signed_type) {
        if (a == std::numeric_limits<int128_t>::min() && b == int128_base_t<S>(-1)) {
            return {int128_base_t<S>(0), conversion_result::success};
        }
    }

    return {a % b, conversion_result::success};
}

template <signedness S>
constexpr safe_result<int128_base_t<S>> safe_shl(const int128_base_t<S>& value, int shift) noexcept
{
    if (shift < 0 || shift >= 128) {
        return {int128_base_t<S>(0), conversion_result::invalid_input};
    }

    if (shift == 0)
        return {value, conversion_result::success};

    const int128_base_t<S> result = value << shift;
    if ((result >> shift) != value) {
        if constexpr (S == signedness::unsigned_type) {
            return {int128_base_t<S>(0), conversion_result::overflow};
        } else {
            return {int128_base_t<S>(0), value.is_negative() ? conversion_result::underflow
                                                             : conversion_result::overflow};
        }
    }

    return {result, conversion_result::success};
}

template <signedness S>
constexpr safe_result<int128_base_t<S>> safe_shr(const int128_base_t<S>& value, int shift) noexcept
{
    if (shift < 0 || shift >= 128) {
        return {int128_base_t<S>(0), conversion_result::invalid_input};
    }
    return {value >> shift, conversion_result::success};
}

// =============================================================================
// Saturating arithmetic
// =============================================================================

template <signedness S>
constexpr int128_base_t<S> saturating_add(const int128_base_t<S>& a,
                                          const int128_base_t<S>& b) noexcept
{
    const auto result = safe_add(a, b);
    if (result.is_valid())
        return result.value;

    if constexpr (S == signedness::unsigned_type) {
        return std::numeric_limits<uint128_t>::max();
    } else {
        return (result.status == conversion_result::overflow)
                   ? std::numeric_limits<int128_t>::max()
                   : std::numeric_limits<int128_t>::min();
    }
}

template <signedness S>
constexpr int128_base_t<S> saturating_sub(const int128_base_t<S>& a,
                                          const int128_base_t<S>& b) noexcept
{
    const auto result = safe_sub(a, b);
    if (result.is_valid())
        return result.value;

    if constexpr (S == signedness::unsigned_type) {
        return int128_base_t<S>(0);
    } else {
        return (result.status == conversion_result::overflow)
                   ? std::numeric_limits<int128_t>::max()
                   : std::numeric_limits<int128_t>::min();
    }
}

template <signedness S>
constexpr int128_base_t<S> saturating_mul(const int128_base_t<S>& a,
                                          const int128_base_t<S>& b) noexcept
{
    const auto result = safe_mul(a, b);
    if (result.is_valid())
        return result.value;

    if constexpr (S == signedness::unsigned_type) {
        return std::numeric_limits<uint128_t>::max();
    } else {
        return (result.status == conversion_result::overflow)
                   ? std::numeric_limits<int128_t>::max()
                   : std::numeric_limits<int128_t>::min();
    }
}

// =============================================================================
// Safe abs (signed only)
// =============================================================================

template <signedness S>
constexpr safe_result<int128_base_t<S>> safe_abs(const int128_base_t<S>& value) noexcept
    requires(S == signedness::signed_type)
{
    if (value == std::numeric_limits<int128_t>::min()) {
        return {int128_base_t<S>(0), conversion_result::overflow};
    }
    return {value.abs(), conversion_result::success};
}

template <signedness S>
constexpr int128_base_t<S> saturating_abs(const int128_base_t<S>& value) noexcept
    requires(S == signedness::signed_type)
{
    const auto result = safe_abs<S>(value);
    return result.is_valid() ? result.value : std::numeric_limits<int128_t>::max();
}

// =============================================================================
// Range utilities
// =============================================================================

template <signedness S>
constexpr bool in_range(const int128_base_t<S>& value, const int128_base_t<S>& min_val,
                        const int128_base_t<S>& max_val) noexcept
{
    return value >= min_val && value <= max_val;
}

template <signedness S>
constexpr int128_base_t<S> clamp(const int128_base_t<S>& value, const int128_base_t<S>& min_val,
                                 const int128_base_t<S>& max_val) noexcept
{
    if (value < min_val)
        return min_val;
    if (value > max_val)
        return max_val;
    return value;
}

} // local close of namespace int128_safe

} // local close of namespace nstd

#endif // INT128_BASE_SAFE_HPP
