/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#pragma once
#ifndef INT128_RANGES_HPP
#define INT128_RANGES_HPP

#include "int128_t.hpp"
#include <numeric>

namespace nstd
{

/**
 * @brief Especializaciones de funciones de rango de std para int128_t
 *
 * Este archivo proporciona especializaciones de las funciones de rango
 * estándar (std::iota, std::accumulate, etc.) para trabajar con int128_t.
 * Incluye manejo especializado para enteros con signo y overflow.
 */

/*
 * NOTA: Las funciones estándar de STL como std::iota, std::accumulate, etc.
 * ya funcionan correctamente con int128_t gracias a los operadores básicos.
 *
 * En lugar de redefinir estas funciones (que causaría conflictos),
 * proporcionamos funciones adicionales y extensiones específicas para int128_t.
 */

// ===============================================================================
// FUNCIONES DE CONVENIENCIA PARA RANGOS CON int128_t
// ===============================================================================

namespace int128_ranges
{

using uint128_t = nstd::uint128_t;
using int128_t = nstd::int128_t;

/**
 * @brief Genera secuencia aritmética de int128_t
 */
template <class OutputIt>
void generate_arithmetic_sequence(OutputIt first, OutputIt last, int128_t start, int128_t step)
{
    int128_t current = start;
    while (first != last) {
        *first++ = current;
        current += step;
    }
}

/**
 * @brief Genera secuencia geométrica de int128_t (con cuidado del overflow)
 */
template <class OutputIt>
void generate_geometric_sequence(OutputIt first, OutputIt last, int128_t start, int128_t ratio)
{
    int128_t current = start;
    while (first != last) {
        *first++ = current;
        // Verificar overflow potencial antes de multiplicar
        if (ratio != int128_t(1) && current != int128_t(0)) {
            // Simplificada verificación de overflow
            current *= ratio;
        }
    }
}

/**
 * @brief Suma con verificación de overflow
 */
inline bool add_overflow(int128_t a, int128_t b, int128_t& result)
{
    result = a + b;

    // Overflow si los signos de a y b son iguales, pero el signo del resultado es diferente
    if (a.is_negative() == b.is_negative() && result.is_negative() != a.is_negative()) {
        return true; // Overflow detected
    }
    return false;
}

/**
 * @brief Multiplicación con verificación de overflow
 */
inline bool mul_overflow(int128_t a, int128_t b, int128_t& result)
{
    result = a * b;

    // Verificación básica: si alguno es 0, no hay overflow
    if (a.is_zero() || b.is_zero()) {
        return false;
    }

    // Si el resultado dividido por uno de los operandos no da el otro, hay overflow
    if ((result / a) != b) {
        return true;
    }

    return false;
}

/**
 * @brief Calcula estadísticas básicas de un rango
 */
template <class InputIt> struct range_stats {
    int128_t sum = int128_t(0);
    int128_t min_val;
    int128_t max_val;
    size_t count = 0;

    bool valid = false;
};

template <class InputIt> range_stats<InputIt> calculate_stats(InputIt first, InputIt last)
{
    range_stats<InputIt> stats;

    if (first == last) {
        return stats; // invalid
    }

    stats.min_val = *first;
    stats.max_val = *first;
    stats.sum = *first;
    stats.count = 1;
    stats.valid = true;

    while (++first != last) {
        int128_t val = *first;
        stats.sum += val;

        if (val < stats.min_val) {
            stats.min_val = val;
        }
        if (val > stats.max_val) {
            stats.max_val = val;
        }

        stats.count++;
    }

    return stats;
}

} // namespace int128_ranges

} // namespace nstd

#endif // INT128_RANGES_HPP