/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

 /**
 * @author Julián Calderón Almendros <julian.calderon.almendros@gmail.com>
 * @version 1.0.0
 * @date 2026-01-05
 * @copyright Boost Software License 1.0
  */
#ifndef INT128_TRAITS_HPP
#define INT128_TRAITS_HPP

#include "../uint128/uint128_traits.hpp" // Para declaraciones base de common_type, hash, etc.
#include "int128_t.hpp"
#include <functional>
#include <type_traits>

namespace nstd
{

// ===============================================================================
// DECLARACIONES BASE (ya declaradas en uint128_traits.hpp pero requeridas aquí)
// ===============================================================================
// No necesitamos redeclararlas si uint128_traits.hpp ya fue incluido

// ===============================================================================
// COMMON TYPE - ESPECIALIZACIONES PARA INT128_T
// ===============================================================================

// int128_t con tipos estándar con signo
template <> struct common_type<int128_t, int64_t> {
    using type = int128_t;
};
template <> struct common_type<int64_t, int128_t> {
    using type = int128_t;
};
template <> struct common_type<int128_t, int32_t> {
    using type = int128_t;
};
template <> struct common_type<int32_t, int128_t> {
    using type = int128_t;
};
template <> struct common_type<int128_t, int16_t> {
    using type = int128_t;
};
template <> struct common_type<int16_t, int128_t> {
    using type = int128_t;
};
template <> struct common_type<int128_t, int8_t> {
    using type = int128_t;
};
template <> struct common_type<int8_t, int128_t> {
    using type = int128_t;
};

// int128_t con tipos estándar sin signo
template <> struct common_type<int128_t, uint64_t> {
    using type = int128_t;
};
template <> struct common_type<uint64_t, int128_t> {
    using type = int128_t;
};
template <> struct common_type<int128_t, uint32_t> {
    using type = int128_t;
};
template <> struct common_type<uint32_t, int128_t> {
    using type = int128_t;
};
template <> struct common_type<int128_t, uint16_t> {
    using type = int128_t;
};
template <> struct common_type<uint16_t, int128_t> {
    using type = int128_t;
};
template <> struct common_type<int128_t, uint8_t> {
    using type = int128_t;
};
template <> struct common_type<uint8_t, int128_t> {
    using type = int128_t;
};

template <> struct common_type<int128_t, int128_t> {
    using type = int128_t;
};

// int128_t con uint128_t
template <> struct common_type<int128_t, uint128_t> {
    using type = int128_t;
};
template <> struct common_type<uint128_t, int128_t> {
    using type = int128_t;
};

// ===============================================================================
// HASH
// ===============================================================================

template <> struct hash<int128_t> {
    size_t operator()(const int128_t& value) const noexcept
    {
        std::hash<uint64_t> hasher;
        return hasher(value.high()) ^ (hasher(value.low()) << 1);
    }
};

// ===============================================================================
// MAKE_SIGNED / MAKE_UNSIGNED - ESPECIALIZACIONES PARA INT128_T
// ===============================================================================

template <> struct make_signed<int128_t> {
    using type = int128_t;
};

template <> struct make_unsigned<int128_t> {
    using type = uint128_t;
};

} // namespace nstd
#endif // INT128_TRAITS_HPP