/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/**
 * @file compiler_detection.hpp
 * @brief Detección de compilador, arquitectura y capacidades
 *
 * Este header proporciona macros para detectar el compilador en uso,
 * la arquitectura objetivo y las capacidades disponibles.
 *
 * @author Julián Calderón Almendros <julian.calderon.almendros@gmail.com>
 * @version 1.0.0
 * @date 2026-01-05
 * @copyright Boost Software License 1.0
 */

#ifndef INTRINSICS_COMPILER_DETECTION_HPP
#define INTRINSICS_COMPILER_DETECTION_HPP

// ============================================================================
// DETECCIÓN DE COMPILADOR
// ============================================================================

// Detectar compilador antes de arquitectura (orden importa)
#if defined(__INTEL_COMPILER) || defined(__INTEL_LLVM_COMPILER) || defined(__ICL) || defined(__ICC)
#define INTRINSICS_COMPILER_INTEL 1
#elif defined(_MSC_VER)
#define INTRINSICS_COMPILER_MSVC 1
#elif defined(__clang__)
#define INTRINSICS_COMPILER_CLANG 1
#elif defined(__GNUC__)
#define INTRINSICS_COMPILER_GCC 1
#else
#define INTRINSICS_COMPILER_UNKNOWN 1
#endif

// Definir 0 para los no detectados
#ifndef INTRINSICS_COMPILER_INTEL
#define INTRINSICS_COMPILER_INTEL 0
#endif
#ifndef INTRINSICS_COMPILER_MSVC
#define INTRINSICS_COMPILER_MSVC 0
#endif
#ifndef INTRINSICS_COMPILER_CLANG
#define INTRINSICS_COMPILER_CLANG 0
#endif
#ifndef INTRINSICS_COMPILER_GCC
#define INTRINSICS_COMPILER_GCC 0
#endif
#ifndef INTRINSICS_COMPILER_UNKNOWN
#define INTRINSICS_COMPILER_UNKNOWN 0
#endif

// ============================================================================
// DETECCIÓN DE ARQUITECTURA
// ============================================================================

#if defined(__x86_64__) || defined(_M_X64) || defined(__amd64__)
#define INTRINSICS_ARCH_X86_64 1
#elif defined(__i386__) || defined(_M_IX86)
#define INTRINSICS_ARCH_X86_32 1
#elif defined(__aarch64__) || defined(_M_ARM64)
#define INTRINSICS_ARCH_ARM64 1
#elif defined(__arm__) || defined(_M_ARM)
#define INTRINSICS_ARCH_ARM32 1
#elif defined(__riscv)
#if __riscv_xlen == 64
#define INTRINSICS_ARCH_RISCV64 1
#else
#define INTRINSICS_ARCH_RISCV32 1
#endif
#elif defined(__powerpc64__) || defined(__ppc64__)
#define INTRINSICS_ARCH_PPC64 1
#else
#define INTRINSICS_ARCH_UNKNOWN 1
#endif

// Definir 0 para arquitecturas no detectadas
#ifndef INTRINSICS_ARCH_X86_64
#define INTRINSICS_ARCH_X86_64 0
#endif
#ifndef INTRINSICS_ARCH_X86_32
#define INTRINSICS_ARCH_X86_32 0
#endif
#ifndef INTRINSICS_ARCH_ARM64
#define INTRINSICS_ARCH_ARM64 0
#endif
#ifndef INTRINSICS_ARCH_ARM32
#define INTRINSICS_ARCH_ARM32 0
#endif
#ifndef INTRINSICS_ARCH_RISCV64
#define INTRINSICS_ARCH_RISCV64 0
#endif
#ifndef INTRINSICS_ARCH_RISCV32
#define INTRINSICS_ARCH_RISCV32 0
#endif
#ifndef INTRINSICS_ARCH_PPC64
#define INTRINSICS_ARCH_PPC64 0
#endif
#ifndef INTRINSICS_ARCH_UNKNOWN
#define INTRINSICS_ARCH_UNKNOWN 0
#endif

// ============================================================================
// DETECCIÓN DE CAPACIDADES (BUILTINS)
// ============================================================================

// GCC/Clang/Intel tienen __has_builtin
#ifdef __has_builtin
#define INTRINSICS_HAS_BUILTIN(x) __has_builtin(x)
#else
#define INTRINSICS_HAS_BUILTIN(x) 0
#endif

// Detectar builtins específicos
#if INTRINSICS_HAS_BUILTIN(__builtin_popcountll)
#define INTRINSICS_HAS_BUILTIN_POPCOUNT 1
#elif INTRINSICS_COMPILER_GCC || INTRINSICS_COMPILER_CLANG || INTRINSICS_COMPILER_INTEL
#define INTRINSICS_HAS_BUILTIN_POPCOUNT 1
#else
#define INTRINSICS_HAS_BUILTIN_POPCOUNT 0
#endif

#if INTRINSICS_HAS_BUILTIN(__builtin_clzll)
#define INTRINSICS_HAS_BUILTIN_CLZ 1
#elif INTRINSICS_COMPILER_GCC || INTRINSICS_COMPILER_CLANG || INTRINSICS_COMPILER_INTEL
#define INTRINSICS_HAS_BUILTIN_CLZ 1
#else
#define INTRINSICS_HAS_BUILTIN_CLZ 0
#endif

#if INTRINSICS_HAS_BUILTIN(__builtin_ctzll)
#define INTRINSICS_HAS_BUILTIN_CTZ 1
#elif INTRINSICS_COMPILER_GCC || INTRINSICS_COMPILER_CLANG || INTRINSICS_COMPILER_INTEL
#define INTRINSICS_HAS_BUILTIN_CTZ 1
#else
#define INTRINSICS_HAS_BUILTIN_CTZ 0
#endif

#if INTRINSICS_HAS_BUILTIN(__builtin_bswap64)
#define INTRINSICS_HAS_BUILTIN_BSWAP 1
#elif INTRINSICS_COMPILER_GCC || INTRINSICS_COMPILER_CLANG || INTRINSICS_COMPILER_INTEL
#define INTRINSICS_HAS_BUILTIN_BSWAP 1
#else
#define INTRINSICS_HAS_BUILTIN_BSWAP 0
#endif

// Detectar __builtin_addcll / __builtin_subcll (GCC/Clang x86-64)
#if INTRINSICS_HAS_BUILTIN(__builtin_addcll) && INTRINSICS_ARCH_X86_64
#define INTRINSICS_HAS_BUILTIN_ADDC 1
#else
#define INTRINSICS_HAS_BUILTIN_ADDC 0
#endif

// ============================================================================
// DETECCIÓN DE HEADERS INTRÍNSECOS
// ============================================================================

#if INTRINSICS_COMPILER_MSVC
#define INTRINSICS_HAS_INTRIN_H 1
#define INTRINSICS_HAS_X86INTRIN_H 0
#define INTRINSICS_HAS_ARM_NEON_H 0
#elif INTRINSICS_ARCH_X86_64 || INTRINSICS_ARCH_X86_32
#define INTRINSICS_HAS_INTRIN_H 0
#define INTRINSICS_HAS_X86INTRIN_H 1
#define INTRINSICS_HAS_ARM_NEON_H 0
#elif INTRINSICS_ARCH_ARM64 || INTRINSICS_ARCH_ARM32
#define INTRINSICS_HAS_INTRIN_H 0
#define INTRINSICS_HAS_X86INTRIN_H 0
#define INTRINSICS_HAS_ARM_NEON_H 1
#else
#define INTRINSICS_HAS_INTRIN_H 0
#define INTRINSICS_HAS_X86INTRIN_H 0
#define INTRINSICS_HAS_ARM_NEON_H 0
#endif

// ============================================================================
// INCLUIR HEADERS NECESARIOS
// ============================================================================

#if INTRINSICS_HAS_INTRIN_H
#include <intrin.h>
#endif

#if INTRINSICS_HAS_X86INTRIN_H
// GCC/Clang en x86-64: <x86intrin.h> incluye todo lo necesario
// Pero los builtins suelen funcionar sin incluir nada
#endif

#if INTRINSICS_HAS_ARM_NEON_H
#include <arm_neon.h>
#endif

// ============================================================================
// DETECCIÓN DE C++20 std::is_constant_evaluated
// ============================================================================

#include <type_traits>

#if defined(__cpp_lib_is_constant_evaluated) && __cpp_lib_is_constant_evaluated >= 201811L
#define INTRINSICS_HAS_IS_CONSTANT_EVALUATED 1
#else
#define INTRINSICS_HAS_IS_CONSTANT_EVALUATED 0
#endif

// ============================================================================
// MACRO HELPER PARA CONSTEXPR
// ============================================================================

/**
 * @def INTRINSICS_IS_CONSTANT_EVALUATED()
 * @brief Verifica si la evaluación es en tiempo de compilación
 */
#if INTRINSICS_HAS_IS_CONSTANT_EVALUATED
#define INTRINSICS_IS_CONSTANT_EVALUATED() std::is_constant_evaluated()
#else
// Fallback: siempre retorna false (seguro pero menos optimizado)
#define INTRINSICS_IS_CONSTANT_EVALUATED() false
#endif

// ============================================================================
// INFORMACIÓN DE RESUMEN
// ============================================================================

/**
 * @page compiler_detection Detección de Compilador y Arquitectura
 *
 * ## Compiladores Detectados
 * - INTRINSICS_COMPILER_INTEL: Intel oneAPI (icx, icpx, icc)
 * - INTRINSICS_COMPILER_MSVC: Microsoft Visual C++
 * - INTRINSICS_COMPILER_CLANG: Clang/LLVM
 * - INTRINSICS_COMPILER_GCC: GNU Compiler Collection
 * - INTRINSICS_COMPILER_UNKNOWN: Compilador no reconocido
 *
 * ## Arquitecturas Soportadas
 * - INTRINSICS_ARCH_X86_64: x86-64 (AMD64, x64)
 * - INTRINSICS_ARCH_X86_32: x86 32-bit (i386, i686)
 * - INTRINSICS_ARCH_ARM64: ARM 64-bit (AArch64)
 * - INTRINSICS_ARCH_ARM32: ARM 32-bit
 * - INTRINSICS_ARCH_RISCV64: RISC-V 64-bit
 * - INTRINSICS_ARCH_RISCV32: RISC-V 32-bit
 * - INTRINSICS_ARCH_PPC64: PowerPC 64-bit
 * - INTRINSICS_ARCH_UNKNOWN: Arquitectura no reconocida
 *
 * ## Capacidades Detectadas
 * - INTRINSICS_HAS_BUILTIN_POPCOUNT: __builtin_popcountll
 * - INTRINSICS_HAS_BUILTIN_CLZ: __builtin_clzll
 * - INTRINSICS_HAS_BUILTIN_CTZ: __builtin_ctzll
 * - INTRINSICS_HAS_BUILTIN_BSWAP: __builtin_bswap64
 * - INTRINSICS_HAS_BUILTIN_ADDC: __builtin_addcll
 *
 * ## Uso
 * @code
 * #if INTRINSICS_COMPILER_MSVC
 *     // Código específico de MSVC
 * #elif INTRINSICS_COMPILER_INTEL
 *     // Código específico de Intel
 * #else
 *     // Fallback genérico
 * #endif
 * @endcode
 */

#endif // INTRINSICS_COMPILER_DETECTION_HPP
