/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#pragma once
#ifndef INT128_RANGES_HPP
#define INT128_RANGES_HPP

#include "int128_t.hpp"
#include <numeric>

/**
 * @brief Especializaciones de funciones de rango de std para int128_t
 *
 * Este archivo proporciona especializaciones de las funciones de rango
 * estándar (std::iota, std::accumulate, etc.) para trabajar con int128_t.
 * Incluye manejo especializado para enteros con signo y overflow.
 */

namespace std
{

/**
 * @brief Especialización de std::iota para int128_t
 * Llena un rango con valores secuenciales incrementales
 */
template <class ForwardIt> void iota(ForwardIt first, ForwardIt last, int128_t value)
{
    while (first != last) {
        *first++ = value;
        ++value;
    }
}

/**
 * @brief Especialización de std::accumulate para int128_t
 */
template <class InputIt> int128_t accumulate(InputIt first, InputIt last, int128_t init)
{
    while (first != last) {
        init = init + *first;
        ++first;
    }
    return init;
}

/**
 * @brief Especialización de std::accumulate con operación personalizada
 */
template <class InputIt, class BinaryOperation>
int128_t accumulate(InputIt first, InputIt last, int128_t init, BinaryOperation op)
{
    while (first != last) {
        init = op(init, *first);
        ++first;
    }
    return init;
}

/**
 * @brief Especialización de std::inner_product para int128_t
 */
template <class InputIt1, class InputIt2>
int128_t inner_product(InputIt1 first1, InputIt1 last1, InputIt2 first2, int128_t init)
{
    while (first1 != last1) {
        init = init + (*first1) * (*first2);
        ++first1;
        ++first2;
    }
    return init;
}

/**
 * @brief Especialización de std::partial_sum para int128_t
 */
template <class InputIt, class OutputIt>
OutputIt partial_sum(InputIt first, InputIt last, OutputIt d_first)
{
    if (first == last)
        return d_first;

    int128_t sum = *first;
    *d_first = sum;

    while (++first != last) {
        sum = sum + *first;
        *++d_first = sum;
    }
    return ++d_first;
}

/**
 * @brief Especialización de std::adjacent_difference para int128_t
 */
template <class InputIt, class OutputIt>
OutputIt adjacent_difference(InputIt first, InputIt last, OutputIt d_first)
{
    if (first == last)
        return d_first;

    int128_t acc = *first;
    *d_first = acc;

    while (++first != last) {
        int128_t val = *first;
        *++d_first = val - acc;
        acc = val;
    }
    return ++d_first;
}

/**
 * @brief Especialización de std::transform_reduce para int128_t
 */
template <class InputIt1, class InputIt2>
int128_t transform_reduce(InputIt1 first1, InputIt1 last1, InputIt2 first2, int128_t init)
{
    while (first1 != last1) {
        init = init + (*first1) * (*first2);
        ++first1;
        ++first2;
    }
    return init;
}

/**
 * @brief Especialización de std::transform_reduce con operaciones personalizadas
 */
template <class InputIt1, class InputIt2, class BinaryOp1, class BinaryOp2>
int128_t transform_reduce(InputIt1 first1, InputIt1 last1, InputIt2 first2, int128_t init,
                          BinaryOp1 reduce_op, BinaryOp2 transform_op)
{
    while (first1 != last1) {
        init = reduce_op(init, transform_op(*first1, *first2));
        ++first1;
        ++first2;
    }
    return init;
}

/**
 * @brief Especialización de std::exclusive_scan para int128_t
 */
template <class InputIt, class OutputIt>
OutputIt exclusive_scan(InputIt first, InputIt last, OutputIt d_first, int128_t init)
{
    while (first != last) {
        int128_t tmp = init;
        init = init + *first;
        ++first;
        *d_first = tmp;
        ++d_first;
    }
    return d_first;
}

/**
 * @brief Especialización de std::inclusive_scan para int128_t
 */
template <class InputIt, class OutputIt>
OutputIt inclusive_scan(InputIt first, InputIt last, OutputIt d_first, int128_t init)
{
    while (first != last) {
        init = init + *first;
        *d_first = init;
        ++first;
        ++d_first;
    }
    return d_first;
}

} // namespace std

// ===============================================================================
// FUNCIONES DE CONVENIENCIA PARA RANGOS CON int128_t
// ===============================================================================

namespace int128_ranges
{

/**
 * @brief Genera secuencia aritmética de int128_t
 */
template <class OutputIt>
void generate_arithmetic_sequence(OutputIt first, OutputIt last, int128_t start, int128_t step)
{
    int128_t current = start;
    while (first != last) {
        *first++ = current;
        current += step;
    }
}

/**
 * @brief Genera secuencia geométrica de int128_t (con cuidado del overflow)
 */
template <class OutputIt>
void generate_geometric_sequence(OutputIt first, OutputIt last, int128_t start, int128_t ratio)
{
    int128_t current = start;
    while (first != last) {
        *first++ = current;
        // Verificar overflow potencial antes de multiplicar
        if (ratio != int128_t(1) && current != int128_t(0)) {
            // Simplificada verificación de overflow
            current *= ratio;
        }
    }
}

/**
 * @brief Suma con verificación de overflow
 */
inline bool add_overflow(int128_t a, int128_t b, int128_t& result)
{
    result = a + b;

    // Overflow si los signos de a y b son iguales, pero el signo del resultado es diferente
    if (a.is_negative() == b.is_negative() && result.is_negative() != a.is_negative()) {
        return true; // Overflow detected
    }
    return false;
}

/**
 * @brief Multiplicación con verificación de overflow
 */
inline bool mul_overflow(int128_t a, int128_t b, int128_t& result)
{
    result = a * b;

    // Verificación básica: si alguno es 0, no hay overflow
    if (a.is_zero() || b.is_zero()) {
        return false;
    }

    // Si el resultado dividido por uno de los operandos no da el otro, hay overflow
    if ((result / a) != b) {
        return true;
    }

    return false;
}

/**
 * @brief Calcula estadísticas básicas de un rango
 */
template <class InputIt> struct range_stats {
    int128_t sum = int128_t(0);
    int128_t min_val;
    int128_t max_val;
    size_t count = 0;

    bool valid = false;
};

template <class InputIt> range_stats<InputIt> calculate_stats(InputIt first, InputIt last)
{
    range_stats<InputIt> stats;

    if (first == last) {
        return stats; // invalid
    }

    stats.min_val = *first;
    stats.max_val = *first;
    stats.sum = *first;
    stats.count = 1;
    stats.valid = true;

    while (++first != last) {
        int128_t val = *first;
        stats.sum += val;

        if (val < stats.min_val) {
            stats.min_val = val;
        }
        if (val > stats.max_val) {
            stats.max_val = val;
        }

        stats.count++;
    }

    return stats;
}

} // namespace int128_ranges

#endif // INT128_RANGES_HPP