/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef INT128_TRAITS_HPP
#define INT128_TRAITS_HPP

#include "int128_t.hpp"
#include <functional>
#include <type_traits>

namespace std
{

// ===============================================================================
// TYPE TRAITS FUNDAMENTALES
// ===============================================================================

/**
 * @brief Especialización para is_integral
 *
 * Marca int128_t como un tipo integral, permitiendo su uso en contextos
 * que requieren tipos enteros.
 */
template <> struct is_integral<int128_t> : true_type {
};

/**
 * @brief Especialización para is_arithmetic
 *
 * Marca int128_t como un tipo aritmético, habilitando operaciones
 * matemáticas estándar.
 */
template <> struct is_arithmetic<int128_t> : true_type {
};

/**
 * @brief Especialización para is_unsigned
 *
 * Marca int128_t como NO siendo un tipo sin signo.
 */
template <> struct is_unsigned<int128_t> : false_type {
};

/**
 * @brief Especialización para is_signed
 *
 * Marca int128_t como un tipo con signo.
 */
template <> struct is_signed<int128_t> : true_type {
};

// ===============================================================================
// TRANSFORMACIÓN DE TIPOS
// ===============================================================================

/**
 * @brief Especialización para make_signed
 *
 * Para int128_t, make_signed devuelve el mismo tipo ya que
 * int128_t ya es con signo.
 */
template <> struct make_signed<int128_t> {
    using type = int128_t;
};

/**
 * @brief Especialización para make_unsigned
 *
 * Convierte int128_t a su equivalente sin signo uint128_t.
 */
template <> struct make_unsigned<int128_t> {
    using type = uint128_t;
};

// ===============================================================================
// TIPOS COMUNES (COMMON TYPES)
// ===============================================================================

/**
 * @brief Especializaciones para common_type con tipos integrales estándar
 *
 * Estas especializaciones permiten que int128_t se use correctamente
 * en templates que dependen de std::common_type.
 */

template <> struct common_type<int128_t, int64_t> {
    using type = int128_t;
};

template <> struct common_type<int64_t, int128_t> {
    using type = int128_t;
};

template <> struct common_type<int128_t, int32_t> {
    using type = int128_t;
};

template <> struct common_type<int32_t, int128_t> {
    using type = int128_t;
};

template <> struct common_type<int128_t, int16_t> {
    using type = int128_t;
};

template <> struct common_type<int16_t, int128_t> {
    using type = int128_t;
};

template <> struct common_type<int128_t, int8_t> {
    using type = int128_t;
};

template <> struct common_type<int8_t, int128_t> {
    using type = int128_t;
};

template <> struct common_type<int128_t, uint64_t> {
    using type = int128_t;
};

template <> struct common_type<uint64_t, int128_t> {
    using type = int128_t;
};

template <> struct common_type<int128_t, uint32_t> {
    using type = int128_t;
};

template <> struct common_type<uint32_t, int128_t> {
    using type = int128_t;
};

template <> struct common_type<int128_t, uint16_t> {
    using type = int128_t;
};

template <> struct common_type<uint16_t, int128_t> {
    using type = int128_t;
};

template <> struct common_type<int128_t, uint8_t> {
    using type = int128_t;
};

template <> struct common_type<uint8_t, int128_t> {
    using type = int128_t;
};

template <> struct common_type<int128_t, int128_t> {
    using type = int128_t;
};

// ===============================================================================
// INTEROPERABILIDAD CON UINT128_T
// ===============================================================================

template <> struct common_type<int128_t, uint128_t> {
    using type = uint128_t; // El tipo sin signo puede representar más valores positivos
};

template <> struct common_type<uint128_t, int128_t> {
    using type = uint128_t;
};

// ===============================================================================
// SOPORTE PARA HASH
// ===============================================================================

/**
 * @brief Especialización de std::hash para int128_t
 *
 * Proporciona una función hash que combina los valores high y low
 * del int128_t para su uso en containers no ordenados como
 * std::unordered_set y std::unordered_map.
 */
template <> struct hash<int128_t> {
    /**
     * @brief Calcula el valor hash de un int128_t
     * @param value Valor a hashear
     * @return Valor hash resultante
     *
     * La implementación combina los hashes de las partes high y low
     * usando XOR y desplazamiento para reducir colisiones.
     */
    size_t operator()(const int128_t& value) const noexcept
    {
        hash<uint64_t> hasher;
        return hasher(value.high()) ^ (hasher(value.low()) << 1);
    }
};

} // namespace std

#endif // INT128_TRAITS_HPP