/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef INT128_HPP
#define INT128_HPP

/**
 * @file int128.hpp
 * @brief Header principal - Incluye toda la biblioteca int128
 *
 * Este header proporciona:
 * - nstd::uint128_t - Entero sin signo de 128 bits
 * - nstd::int128_t  - Entero con signo de 128 bits
 *
 * Ambos tipos son aliases del template unificado:
 *   template<signedness S> class int128_base_t;
 *
 * @example
 * @code
 * #include <int128.hpp>
 * using namespace nstd;
 *
 * uint128_t a = 12345678901234567890ULL;
 * int128_t b = -42;
 *
 * auto sum = a + uint128_t(100);
 * auto product = b * int128_t(2);
 * @endcode
 *
 * @author Julián Calderón Almendros
 * @version 1.66
 * @date 2026-01-08
 */

// Core template
#include "int128_base_tt.hpp"

// Type traits y limits
#include "int128_base_limits.hpp"
#include "int128_base_traits.hpp"
#include "int128_base_traits_specializations.hpp"

// C++20 concepts
#include "int128_base_concepts.hpp"

// Funcionalidad extendida
#include "int128_base_algorithm.hpp"
#include "int128_base_bits.hpp"
#include "int128_base_cmath.hpp"
#include "int128_base_numeric.hpp"

// I/O y formateo
#include "int128_base_format.hpp"
#include "int128_base_iostreams.hpp"

// Rangos y seguridad
#include "int128_base_ranges.hpp"
#include "int128_base_safe.hpp"

// Thread safety (opcional, requiere -pthread -latomic)
// #include "int128_base_thread_safety.hpp"

#endif // INT128_HPP
