/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef UINT128_SIMPLE_TRAITS_HPP
#define UINT128_SIMPLE_TRAITS_HPP

/**
 * @brief Header de conveniencia que incluye todas las especializaciones de traits
 *
 * Este archivo incluye todos los módulos de traits necesarios para que uint128_t
 * sea completamente compatible con la biblioteca estándar de C++.
 *
 * Para usar las funcionalidades completas de uint128_t, simplemente incluir:
 * #include "uint128_simple_traits.hpp"
 */

// Incluir módulos en orden correcto de dependencia
#include "uint128_limits.hpp"
#include "uint128_numeric.hpp"
#include "uint128_t.hpp"
#include "uint128_traits.hpp"
// Concepts y algorithms requieren que traits estén definidos primero
#include "uint128_algorithm.hpp"
#include "uint128_concepts.hpp"
#include "uint128_ranges_clean.hpp" // Funciones de rango especializadas

/**
 * @brief Verificaciones de compilación
 *
 * Estas verificaciones se ejecutan en tiempo de compilación para
 * asegurar que todas las especializaciones están correctamente definidas.
 */
namespace uint128_simple_traits_checks
{
// Verificar que los modules están disponibles
static_assert(std::numeric_limits<uint128_t>::is_specialized,
              "std::numeric_limits debe estar especializado");
static_assert(std::is_integral_v<uint128_t>, "uint128_t debe ser reconocido como integral");
static_assert(std::is_unsigned_v<uint128_t>, "uint128_t debe ser reconocido como unsigned");
static_assert(std::is_same_v<std::make_unsigned_t<uint128_t>, uint128_t>,
              "make_unsigned debe funcionar correctamente");

// Verificar conceptos C++20
static_assert(std::integral<uint128_t>, "uint128_t debe satisfacer std::integral");
static_assert(std::unsigned_integral<uint128_t>,
              "uint128_t debe satisfacer std::unsigned_integral");

} // namespace uint128_simple_traits_checks

#endif // UINT128_SIMPLE_TRAITS_HPP