/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef UINT128_TRAITS_HPP
#define UINT128_TRAITS_HPP

#include "uint128_t.hpp"
#include <functional>
#include <type_traits>

namespace std
{

// ===============================================================================
// TYPE TRAITS FUNDAMENTALES
// ===============================================================================

/**
 * @brief Especialización para is_integral
 *
 * Marca uint128_t como un tipo integral, permitiendo su uso en contextos
 * que requieren tipos enteros.
 */
template <> struct is_integral<uint128_t> : true_type {
};

/**
 * @brief Especialización para is_arithmetic
 *
 * Marca uint128_t como un tipo aritmético, habilitando operaciones
 * matemáticas estándar.
 */
template <> struct is_arithmetic<uint128_t> : true_type {
};

/**
 * @brief Especialización para is_unsigned
 *
 * Marca uint128_t como un tipo sin signo.
 */
template <> struct is_unsigned<uint128_t> : true_type {
};

/**
 * @brief Especialización para is_signed
 *
 * Marca uint128_t como NO siendo un tipo con signo.
 */
template <> struct is_signed<uint128_t> : false_type {
};

// ===============================================================================
// TRAITS DE TRIVIALIDAD
// ===============================================================================

/**
 * @brief uint128_t es trivialmente copiable
 *
 * Con constructores eliminados, ahora es trivialmente copiable.
 */
template <> struct is_trivially_copyable<uint128_t> : true_type {
};

/**
 * @brief uint128_t es trivialmente constructible por defecto
 *
 * Solo tiene constructor por defecto trivial.
 */
template <> struct is_trivially_default_constructible<uint128_t> : false_type {
};

/**
 * @brief uint128_t es trivialmente constructible por copia
 *
 * Puede ser copiado sin ejecutar código de constructor.
 */
template <> struct is_trivially_copy_constructible<uint128_t> : true_type {
};

/**
 * @brief uint128_t es trivialmente constructible por movimiento
 *
 * Puede ser movido sin ejecutar código de constructor.
 */
template <> struct is_trivially_move_constructible<uint128_t> : true_type {
};

/**
 * @brief uint128_t es trivialmente asignable por copia
 *
 * Puede ser asignado por copia usando memcpy.
 */
template <> struct is_trivially_copy_assignable<uint128_t> : true_type {
};

/**
 * @brief uint128_t es trivialmente asignable por movimiento
 *
 * Puede ser asignado por movimiento sin código especial.
 */
template <> struct is_trivially_move_assignable<uint128_t> : true_type {
};

/**
 * @brief uint128_t es trivialmente destructible
 *
 * No requiere código de destructor especial.
 */
template <> struct is_trivially_destructible<uint128_t> : true_type {
};

/**
 * @brief uint128_t es un tipo trivial
 *
 * Combina todas las propiedades triviales: constructible, copiable,
 * asignable y destructible trivialmente.
 */
template <> struct is_trivial<uint128_t> : false_type {
};

/**
 * @brief uint128_t tiene layout estándar
 *
 * Garantiza que tiene el mismo layout que una estructura C equivalente.
 */
template <> struct is_standard_layout<uint128_t> : true_type {
};

/**
 * @brief uint128_t es un tipo POD (Plain Old Data)
 *
 * Combina ser trivial y tener layout estándar.
 */
template <> struct is_pod<uint128_t> : true_type {
};

// ===============================================================================
// TRANSFORMACIÓN DE TIPOS
// ===============================================================================

/**
 * @brief Especialización para make_unsigned
 *
 * Para uint128_t, make_unsigned devuelve el mismo tipo ya que
 * uint128_t ya es sin signo.
 */
template <> struct make_unsigned<uint128_t> {
    using type = uint128_t;
};

/**
 * @brief Especialización para make_signed
 *
 * NOTA: Esta especialización requiere la implementación de int128_t.
 * Actualmente está comentada hasta que int128_t esté disponible.
 *
 * template <> struct make_signed<uint128_t> {
 *     using type = int128_t;
 * };
 */

// ===============================================================================
// TIPOS COMUNES (COMMON TYPES)
// ===============================================================================

/**
 * @brief Especializaciones para common_type con tipos integrales estándar
 *
 * Estas especializaciones permiten que uint128_t se use correctamente
 * en templates que dependen de std::common_type.
 */

template <> struct common_type<uint128_t, uint64_t> {
    using type = uint128_t;
};

template <> struct common_type<uint64_t, uint128_t> {
    using type = uint128_t;
};

template <> struct common_type<uint128_t, uint32_t> {
    using type = uint128_t;
};

template <> struct common_type<uint32_t, uint128_t> {
    using type = uint128_t;
};

template <> struct common_type<uint128_t, uint16_t> {
    using type = uint128_t;
};

template <> struct common_type<uint16_t, uint128_t> {
    using type = uint128_t;
};

template <> struct common_type<uint128_t, uint8_t> {
    using type = uint128_t;
};

template <> struct common_type<uint8_t, uint128_t> {
    using type = uint128_t;
};

template <> struct common_type<uint128_t, int> {
    using type = uint128_t;
};

template <> struct common_type<int, uint128_t> {
    using type = uint128_t;
};

template <> struct common_type<uint128_t, long> {
    using type = uint128_t;
};

template <> struct common_type<long, uint128_t> {
    using type = uint128_t;
};

template <> struct common_type<uint128_t, uint128_t> {
    using type = uint128_t;
};

// ===============================================================================
// SOPORTE PARA HASH
// ===============================================================================

/**
 * @brief Especialización de std::hash para uint128_t
 *
 * Proporciona una función hash que combina los valores high y low
 * del uint128_t para su uso en containers no ordenados como
 * std::unordered_set y std::unordered_map.
 */
template <> struct hash<uint128_t> {
    /**
     * @brief Calcula el valor hash de un uint128_t
     * @param value Valor a hashear
     * @return Valor hash resultante
     *
     * La implementación combina los hashes de las partes high y low
     * usando XOR y desplazamiento para reducir colisiones.
     */
    size_t operator()(const uint128_t& value) const noexcept
    {
        hash<uint64_t> hasher;
        return hasher(value.high()) ^ (hasher(value.low()) << 1);
    }
};

} // namespace std

#endif // UINT128_TRAITS_HPP